### ISSUE TITLE
青龙环境下cookie的配置问题

### ISSUE THREAD

**Issue by taklele** [Oreomeow/bili#38]
尝试过很多次，总是不成功，日志里显示如下错误
`
2022-06-29 18:42:30.584 INFO  t.m.BiliMain - 使用自定义目录的配置文件
2022-06-29 18:42:30.585 INFO  t.m.c.ConfigLoader - 未在 ：/ql/data/config/bili_config.json 目录读取到配置文件
2022-06-29 18:42:30.585 INFO  t.m.c.ConfigLoader - 未在配置文件中配置cookies
2022-06-29 18:42:30.607 INFO  t.m.t.DailyTask - ------登录检查开始------
2022-06-29 18:42:31.307 WARN  t.m.t.UserCheck - Cookies可能失效了,请仔细检查配置中的Cookies是否有效
2022-06-29 18:42:31.311 INFO  t.m.t.ServerPush - 未配置正确的ftKey和chatId,本次执行将不推送日志
Exception in thread "main" java.lang.ExceptionInInitializerError
	at top.misec.task.UserCheck.run(UserCheck.java:42)
	at top.misec.task.DailyTask.lambda$0(DailyTask.java:69)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:66)
	at top.misec.BiliMain.main(BiliMain.java:40)
Caused by: java.lang.NullPointerException
	at top.misec.config.BiliVerify.getDedeUserId(BiliVerify.java:41)
	at top.misec.task.GetVideoId.queryDynamicNew(GetVideoId.java:77)
	at top.misec.task.GetVideoId.<init>(GetVideoId.java:29)
	at top.misec.task.TaskInfoHolder.<clinit>(TaskInfoHolder.java:21)
	... 5 more

## 执行结束... 2022-06-29 18:42:31 耗时 3 秒
`

请问cookie哪里需要写'cookie' 或 'buvid3' 吗？尝试过删除或保留一个都不行。
我的cookie大概这样
![Snipaste_2022-06-29_18-43-56](https://user-images.githubusercontent.com/2526519/176418513-5a0b11fe-1834-4dc6-b7f0-f1ca50ae461d.png)

**Comment by Oreomeow** [comment]
示例如下

```
buvid_fp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; DedeUserID=xxxxxxxxx; DedeUserID__ckMd5=xxxxxxxxxxxxxxxx; SESSDATA=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; bili_jct=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sid=xxxxxxxx; buvid_fp_plain=xxxxxxxxx; i-wanna-go-back=xx; innersign=x; b_timer=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; fingerprint=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; b_lsid=xxxxxxxxxxxxxxxxxxxxx; b_ut=x; rpdid=xxxxxxxxxxxxxxxxxxxxxxxxx; _uuid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; buvid4=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; buvid3=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
```

**Comment by taklele** [comment]
是我搞错青龙的配置了，谢谢！
